project_name: journal
builds:
  - id: journal
    binary: journal
    main: ./cmd/journal
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - id: archive
    format: tar.gz
    files:
      - LICENSE
checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
release:
  github:
    owner: ''
    name: ''
